/* --COPYRIGHT--,BSD
 * Copyright (c) 2016, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * --/COPYRIGHT--*/


// Generated by MSP USB Descriptor Tool: Tue Feb 03 13:27:09 CST 2015

/*-----------------------------------------------------------------------------+
| Include files 
|-----------------------------------------------------------------------------*/
#include <USB_API/USB_Common/device.h>
#include <USB_API/USB_Common/defMSP430USB.h>
#include <USB_API/USB_Common/usb.h>              // USB-specific Data Structures
#include "descriptors.h"
#include <USB_API/USB_CDC_API/UsbCdc.h>
#include <USB_API/USB_HID_API/UsbHidReq.h>


/*-----------------------------------------------------------------------------+
| Device Descriptor 
|-----------------------------------------------------------------------------*/
uint8_t const abromDeviceDescriptor[SIZEOF_DEVICE_DESCRIPTOR] = {
    18,               // Length of this descriptor
    1, // DESC_TYPE_DEVICE,                       // Type code of this descriptor
    0x10, 0x01,                             // Release of USB spec
    0x00,                                   // Device's base class code
    0x00,                                   // Device's sub class code
    0x00,                                   // Device's protocol type code
    8,                        // End point 0's packet size
    USB_VID&0xFF, USB_VID>>8,               // Vendor ID for device, TI=0x0451
                                            // You can order your own VID at www.usb.org"
    USB_PID&0xFF, USB_PID>>8,               // Product ID for device,
                                            // this ID is to only with this example
    // VER_FW_L, VER_FW_H,                     // Revision level of device
    0x01, 0x00,
    1,                                      // Index of manufacturer name string desc
    2,                                      // Index of product name string desc
    // USB_STR_INDEX_SERNUM,                   // Index of serial number string desc
    0,
    1                                       //  Number of configurations supported
};

/*-----------------------------------------------------------------------------+
| Configuration Descriptor                                                     |
|-----------------------------------------------------------------------------*/


const char abromConfigurationDescriptorGroup[] = {
    9, // sizeof(usbDescrConfig): length of descriptor in bytes
    2, // descriptor type
    101,
    0, // total length of data returned (including inlined descriptors)
    2, // number of interfaces in this configuration
    1, // index of this configuration
    0, // configuration name string index
    USB_SUPPORT_SELF_POWERED | USB_SUPPORT_REM_WAKE,   // bmAttributes, bus power, remote wakeup
    USB_MAX_POWER,                                      // Max. Power Consumption
    //INTERFACE DESCRIPTOR (9 bytes)
    0x09,
    0x04,
    0x00,
    0x00,
    0x00,
    0x01,
    0x01,
    0x00,
    0x00,

    //Class-specific AC Interface Descriptor (9)
    0x09,
    0x24,
    0x01,
    0x00,
    0x01,
    0x09, 0x00,
    0x01,
    0x01,

    //MIDIStreaming Interface Descriptors
    //Standard MS Interface Descriptor (9)
    0x09,
    0x04,
    0x01,
    0x00,
    0x02,
    0x01,
    0x03,
    0x00,
    0x00,

    //Class-specific MS Interface Descriptor (7)
    0x07,
    0x24,
    0x01,
    0x00, 0x01,
    0x41, 0x00,

    //MIDI IN Jack Descriptor (6)
    0x06,
    0x24,
    0x02,
    0x01,
    0x01,
    0x00,

    //MIDI IN Jack Descriptor (6)
    0x06,
    0x24,
    0x02,
    0x02,
    0x02,
    0x00,

    //MIDI OUT Jack Descriptor (9)
    0x09,
    0x24,
    0x03,
    0x01,
    0x03,
    0x01,
    0x02,
    0x01,
    0x00,

    //MIDI OUT Jack Descriptor (9)
    0x09,
    0x24,
    0x03,
    0x02,
    0x04,
    0x01,
    0x01,
    0x01,
    0x00,

    // Standard Bulk OUT (9)
    0x09,
    0x05,
    0x01,
    0x02,
    0x40, 0x00,
    0x00,
    0x00,
    0x00,

    // Class MS Bulk OUT (5)
    0x05,
    0x25,
    0x01,
    0x01,
    0x01,

    // Standard Bulk IN (9)
    0x09,
    0x05,
    0x81,
    0x02,
    0x40, 0x00,
    0x00,
    0x00,
    0x00,

    // Class MS Bulk IN (5)
    0x05,
    0x25,
    0x01,
    0x01,
    0x03
/*
// B.3 AudioControl Interface Descriptors
// The AudioControl interface describes the device structure (audio function topology)
// and is used to manipulate the Audio Controls. This device has no audio function
// incorporated. However, the AudioControl interface is mandatory and therefore both
// the standard AC interface descriptor and the classspecific AC interface descriptor
// must be present. The class-specific AC interface descriptor only contains the header
// descriptor.

// B.3.1 Standard AC Interface Descriptor
// The AudioControl interface has no dedicated endpoints associated with it. It uses the
// default pipe (endpoint 0) for all communication purposes. Class-specific AudioControl
// Requests are sent using the default pipe. There is no Status Interrupt endpoint provided.
    9, // sizeof(usbDescrConfig): length of descriptor in bytes
    2, // descriptor type
    101,
    0, // total length of data returned (including inlined descriptors)
    2, // number of interfaces in this configuration
    1, // index of this configuration
    0, // configuration name string index
    USB_SUPPORT_SELF_POWERED | USB_SUPPORT_REM_WAKE,   // bmAttributes, bus power, remote wakeup
    USB_MAX_POWER,                                      // Max. Power Consumption
    9, // sizeof(usbDescrInterface): length of descriptor in bytes
    2, // descriptor type
    0, // index of this interface
    0, // alternate setting for this interface
    0, // endpoints excl 0: number of endpoint descriptors to follow
    1, //
    1, //
    0, //
    0, // string index for interface

// B.3.2 Class-specific AC Interface Descriptor
// The Class-specific AC interface descriptor is always headed by a Header descriptor
// that contains general information about the AudioControl interface. It contains all
// the pointers needed to describe the Audio Interface Collection, associated with the
// described audio function. Only the Header descriptor is present in this device
// because it does not contain any audio functionality as such.
    9, // sizeof(usbDescrCDC_HeaderFn): length of descriptor in bytes
    36, // descriptor type
    1, // header functional descriptor
    0x0,
    0x01, // bcdADC
    9,
    0, // wTotalLength
    1, //
    1, //

    // B.4 MIDIStreaming Interface Descriptors
// B.4.1 Standard MS Interface Descriptor
    9, // length of descriptor in bytes
    2, // descriptor type
    1, // index of this interface
    0, // alternate setting for this interface
    2, // endpoints excl 0: number of endpoint descriptors to follow
    1, // AUDIO
    3, // MS
    0, // unused
    0, // string index for interface

// B.4.2 Class-specific MS Interface Descriptor
    7, // length of descriptor in bytes
    36, // descriptor type
    1, // header functional descriptor
    0x0,
    0x01, // bcdADC
    65,
    0, // wTotalLength
// B.4.3 MIDI IN Jack Descriptor
    6, // bLength
    36, // descriptor type
    2, // MIDI_IN_JACK desc subtype
    1, // EMBEDDED bJackType
    1, // bJackID
    0, // iJack
    6, // bLength
    36, // descriptor type
    2, // MIDI_IN_JACK desc subtype
    2, // EXTERNAL bJackType
    2, // bJackID
    0, // iJack
//B.4.4 MIDI OUT Jack Descriptor
    9, // length of descriptor in bytes
    36, // descriptor type
    3, // MIDI_OUT_JACK descriptor
    1, // EMBEDDED bJackType
    3, // bJackID
    1, // No of input pins
    2, // BaSourceID
    1, // BaSourcePin
    0, // iJack

    9, // bLength of descriptor in bytes
    36, // bDescriptorType
    3, // MIDI_OUT_JACK bDescriptorSubtype
    2, // EXTERNAL bJackType
    4, // bJackID
    1, // bNrInputPins
    1, // baSourceID (0)
    1, // baSourcePin (0)
    0, // iJack

//B.5 Bulk OUT Endpoint Descriptors
//B.5.1 Standard Bulk OUT Endpoint Descriptor
    9, // bLenght
    5, // bDescriptorType = endpoint
    0x1, // bEndpointAddress OUT endpoint number 1
    3, // bmAttributes: 2:Bulk, 3:Interrupt endpoint
    8,
    0, // wMaxPacketSize
    10, // bInterval in ms
    0, // bRefresh
    0, // bSyncAddress
// B.5.2 Class-specific MS Bulk OUT Endpoint Descriptor
    5, // bLength of descriptor in bytes
    37, // bDescriptorType
    1, // bDescriptorSubtype
    1, // bNumEmbMIDIJack
    1, // baAssocJackID (0)

//B.6 Bulk IN Endpoint Descriptors
//B.6.1 Standard Bulk IN Endpoint Descriptor
    9, // bLenght
    5, // bDescriptorType = endpoint
    0x81, // bEndpointAddress IN endpoint number 1
    3, // bmAttributes: 2: Bulk, 3: Interrupt endpoint
    8,
    0, // wMaxPacketSize
    10, // bInterval in ms
    0, // bRefresh
    0, // bSyncAddress

// B.6.2 Class-specific MS Bulk IN Endpoint Descriptor
    5, // bLength of descriptor in bytes
    37, // bDescriptorType
    1, // bDescriptorSubtype
    1, // bNumEmbMIDIJack (0)
    3, // baAssocJackID (0) */
};

/*-----------------------------------------------------------------------------+
| String Descriptor                                                            |
|-----------------------------------------------------------------------------*/
uint8_t const abromStringDescriptor[] = {
    // String index0, language support

    4,        // Length of language descriptor ID
    3,        // LANGID tag
    0x09, 0x04,    // 0x0409 for English


    // String index1, Manufacturer

    36,        // Length of this string descriptor
    3,        // bDescriptorType
    'T',0x00,'e',0x00,'x',0x00,'a',0x00,'s',0x00,' ',0x00,
    'I',0x00,'n',0x00,'s',0x00,'t',0x00,'r',0x00,'u',0x00,
    'm',0x00,'e',0x00,'n',0x00,'t',0x00,'s',0x00,

    // String index2, Product

    38,        // Length of this string descriptor
    3,        // bDescriptorType
    'M',0x00,'S',0x00,'P',0x00,'4',0x00,'3',0x00,'0',0x00,
    '-',0x00,'U',0x00,'S',0x00,'B',0x00,' ',0x00,'E',0x00,
    'x',0x00,'a',0x00,'m',0x00,'p',0x00,'l',0x00,'e',0x00,

    // String index3, Serial Number

    4,        // Length of this string descriptor
    3,        // bDescriptorType
    '0',0x00,

    // String index4, Configuration String

    22,        // Length of this string descriptor
    3,        // bDescriptorType
    'M',0x00,'S',0x00,'P',0x00,'4',0x00,'3',0x00,'0',0x00,
    ' ',0x00,'U',0x00,'S',0x00,'B',0x00,


    // String index5, Interface String
    38,        // Length of this string descriptor
    3,        // bDescriptorType
    'M',0x00,'S',0x00,'P',0x00,'4',0x00,'3',0x00,'0',0x00,
    '-',0x00,'U',0x00,'S',0x00,'B',0x00,' ',0x00,'E',0x00,
    'x',0x00,'a',0x00,'m',0x00,'p',0x00,'l',0x00,'e',0x00
};



/**** Populating the endpoint information handle here ****/
const struct tUsbHandle stUsbHandle[]=
{
    {
        /* CDC0_INEP_ADDR,
        CDC0_OUTEP_ADDR,
        1,
        CDC_CLASS,
        IEP1_X_BUFFER_ADDRESS,
        IEP1_Y_BUFFER_ADDRESS,
        OEP2_X_BUFFER_ADDRESS,
        OEP2_Y_BUFFER_ADDRESS,
        IEP2_X_BUFFER_ADDRESS,
        IEP2_Y_BUFFER_ADDRESS */
         CDC0_INEP_ADDR,
         CDC0_OUTEP_ADDR,
         1,
         CDC_CLASS,
         IEP2_X_BUFFER_ADDRESS,
         IEP2_Y_BUFFER_ADDRESS,
         OEP1_X_BUFFER_ADDRESS,
         OEP1_Y_BUFFER_ADDRESS,
         IEP1_X_BUFFER_ADDRESS,
         IEP1_Y_BUFFER_ADDRESS
    }

    
        
            
};

//-------------DEVICE REQUEST LIST---------------------------------------------

const tDEVICE_REQUEST_COMPARE tUsbRequestList[] = 
{

    {
        //---- CDC0Class Requests -----//
        // GET LINE CODING
        USB_REQ_TYPE_INPUT | USB_REQ_TYPE_CLASS | USB_REQ_TYPE_INTERFACE,
        USB_CDC_GET_LINE_CODING,
        0x00,0x00,                                 // always zero
        CDC0_COMM_INTERFACE,0x00,                 // CDC interface is0
        0x07,0x00,                                 // Size of Structure (data length)
        0xff,&usbGetLineCoding,
    },
    {
        // SET LINE CODING
        USB_REQ_TYPE_OUTPUT | USB_REQ_TYPE_CLASS | USB_REQ_TYPE_INTERFACE,
        USB_CDC_SET_LINE_CODING,
        0x00,0x00,                                 // always zero
        CDC0_COMM_INTERFACE,0x00,                  // CDC interface is 0
        0x07,0x00,                                 // Size of Structure (data length)
        0xff,&usbSetLineCoding,
    },
    {
        // SET CONTROL LINE STATE
        USB_REQ_TYPE_OUTPUT | USB_REQ_TYPE_CLASS | USB_REQ_TYPE_INTERFACE,
        USB_CDC_SET_CONTROL_LINE_STATE,
        0xff,0xff,                                 // Contains data
        CDC0_COMM_INTERFACE,0x00,                 // CDC interface is 0
        0x00,0x00,                                 // No further data
        0xcf,&usbSetControlLineState,
        },


    {
        //---- USB Standard Requests -----//
            // clear device feature
            USB_REQ_TYPE_OUTPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_DEVICE,
            USB_REQ_CLEAR_FEATURE,
            FEATURE_REMOTE_WAKEUP,0x00,         // feature selector
            0x00,0x00,
            0x00,0x00,
            0xff,&usbClearDeviceFeature,
    },
    {

            // clear endpoint feature
            USB_REQ_TYPE_OUTPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_ENDPOINT,
            USB_REQ_CLEAR_FEATURE,
            FEATURE_ENDPOINT_STALL,0x00,
            0xff,0x00,
            0x00,0x00,
            0xf7,&usbClearEndpointFeature,
    },
    {
            // get configuration
            USB_REQ_TYPE_INPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_DEVICE,
            USB_REQ_GET_CONFIGURATION,
            0x00,0x00, 
            0x00,0x00, 
            0x01,0x00,
            0xff,&usbGetConfiguration,
    },
    {
            // get device descriptor
            USB_REQ_TYPE_INPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_DEVICE,
            USB_REQ_GET_DESCRIPTOR,
            0xff,DESC_TYPE_DEVICE,              // bValueL is index and bValueH is type
            0xff,0xff,
            0xff,0xff,
            0xd0,&usbGetDeviceDescriptor,
    },
    {
            // get configuration descriptor
            USB_REQ_TYPE_INPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_DEVICE,
            USB_REQ_GET_DESCRIPTOR,
            0xff,DESC_TYPE_CONFIG,              // bValueL is index and bValueH is type
            0xff,0xff,
            0xff,0xff,
            0xd0,&usbGetConfigurationDescriptor,
    },
    {
            // get string descriptor
            USB_REQ_TYPE_INPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_DEVICE,
            USB_REQ_GET_DESCRIPTOR,
            0xff,DESC_TYPE_STRING,              // bValueL is index and bValueH is type
            0xff,0xff,
            0xff,0xff,
            0xd0,&usbGetStringDescriptor,
    },
    {
           // get interface
            USB_REQ_TYPE_INPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_INTERFACE,
            USB_REQ_GET_INTERFACE,
            0x00,0x00,
            0xff,0xff,
            0x01,0x00,
            0xf3,&usbGetInterface,
    },
    {
            // get device status
            USB_REQ_TYPE_INPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_DEVICE,
            USB_REQ_GET_STATUS,
            0x00,0x00,
            0x00,0x00,
            0x02,0x00,
            0xff,&usbGetDeviceStatus, 
    },
    {
            // get interface status
            USB_REQ_TYPE_INPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_INTERFACE,
            USB_REQ_GET_STATUS,
            0x00,0x00,
            0xff,0x00,
            0x02,0x00,
            0xf7,&usbGetInterfaceStatus,
    },
    {
            // get endpoint status
            USB_REQ_TYPE_INPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_ENDPOINT,
            USB_REQ_GET_STATUS,
            0x00,0x00,
            0xff,0x00,
            0x02,0x00,
            0xf7,&usbGetEndpointStatus,
    },
    {
            // set address
            USB_REQ_TYPE_OUTPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_DEVICE,
            USB_REQ_SET_ADDRESS,
            0xff,0x00,
            0x00,0x00,
            0x00,0x00,
            0xdf,&usbSetAddress,
    },
    {
            // set configuration
            USB_REQ_TYPE_OUTPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_DEVICE,
            USB_REQ_SET_CONFIGURATION,
            0xff,0x00,
            0x00,0x00,
            0x00,0x00,
            0xdf,&usbSetConfiguration,
    },
    {
           // set device feature
            USB_REQ_TYPE_OUTPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_DEVICE,
            USB_REQ_SET_FEATURE,
            0xff,0x00,                      // feature selector
            0x00,0x00,
            0x00,0x00,
            0xdf,&usbSetDeviceFeature,
    },
    {
            // set endpoint feature
            USB_REQ_TYPE_OUTPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_ENDPOINT,
            USB_REQ_SET_FEATURE,
            0xff,0x00,                      // feature selector
            0xff,0x00,                      // endpoint number <= 127
            0x00,0x00,
            0xd7,&usbSetEndpointFeature,
    },
    {
            // set interface
            USB_REQ_TYPE_OUTPUT | USB_REQ_TYPE_STANDARD | USB_REQ_TYPE_INTERFACE,
            USB_REQ_SET_INTERFACE,
            0xff,0x00,                      // feature selector
            0xff,0x00,                      // interface number
            0x00,0x00,
            0xd7,&usbSetInterface,
    },
    {

            // end of usb descriptor -- this one will be matched to any USB request
            // since bCompareMask is 0x00.
            0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff, 
            0x00,&usbInvalidRequest     // end of list
    }
	
};


/*-----------------------------------------------------------------------------+
| END OF Descriptor.c FILE
|-----------------------------------------------------------------------------*/


//Released_Version_5_20_06_02
